on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      message:
        type: string
        default: ""
        required: true

jobs:
  discord-message:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Notify Discord"
        uses: discord-action/message@v2
        env:
          MESSAGE: ${{ inputs.message }}
        with:
          webhookUrl: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          message: |
            Somebody pushed ${{ github.event.head_commit.id }}
            Ran by ${{ github.workflow.id }}
