on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      message:
        type: string
        default: ""
        required: true

jobs:
  discord-message:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Notify Discord"
        if: ${{ ! contains(github.event.head_commit.message, '[x]') }}
        uses: discord-action/message@v2
        env:
          MESSAGE: ${{ inputs.message }}
          DEFAULT: Somebody pushed ${{ github.event.head_commit.id }}
        with:
          webhookUrl: "${{ secrets.DISCORD_WEBHOOK_URL }}"
          message: "${{ env.MESSAGE || env.DEFAULT }}"
