on: push

jobs:
  failing:
    runs-on: "ubuntu-latest"
    steps:
      - name: Failing step
        id: demo
        run: exit 1
      - name: The demo step has failed
        if: ${{ failure() && steps.demo.conclusion == 'failure' }}
