on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      message:
        type: string
        default: ""
        required: true
      discordWebhookUrl:
        type: string
        default: ""
        required: false

jobs:
  notifikacija:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Notify Discord"
        if: ${{ !github.event.head_commit.message || github.event.head_commit.message && !contains(github.event.head_commit.message, '[x]') }}
        uses: discord-action/message@v2
        env:
          MESSAGE: ${{ inputs.message }}
          DEFAULT: Somebody pushed ${{ github.event.head_commit.id }}
        with:
          webhookUrl: "${{ secrets.DISCORD_WEBHOOK_URL  }}"
          message: "${{ env.MESSAGE || env.DEFAULT }}"
